version: '3'
services:
  web:
    build: .
    ports:
      - "81:8080"
    environment:
      USER_DB: ${USER_DB}
      PASSWORD_DB: ${PASSWORD_DB}
      URL_DB: ${URL_DB}
    depends_on:
      db_schedule:
        condition: service_healthy
  db_schedule: # это по-факту название контейнера, его же нужно и прописывать в jdbcUrl (не localhost)
    image: "postgres:15.2"
    environment:
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
    volumes:
      - pg-volume-prod:/var/lib/postgresql/data/
volumes:
  pg-volume-prod: {}