version: '3'
services:
  db_schedule:
    image: "postgres:15.2"
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg-volume:/var/lib/postgresql/data/
volumes:
  pg-volume: {}